python manage.py startapp accounts
python manage.py startapp users
python manage.py startapp customers
python manage.py startapp leads
python manage.py startapp opportunities
python manage.py startapp tasks
python manage.py startapp meetings
python manage.py startapp reports
python manage.py startapp notifications
python manage.py startapp dashboard
python manage.py startapp audit