# Generated by Django 5.2 on 2026-07-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Salespeople",
            fields=[
                ("snum", models.IntegerField(primary_key=True, serialize=False)),
                ("sname", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=20)),
                ("comm", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
